# Generated by Django 4.2.7 on 2023-11-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mycategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCategory',
        ),
    ]
