# Generated by Django 4.2.7 on 2023-11-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desciption',
            new_name='description',
        ),
    ]
